name: test_commerce
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  responsive_sizer: ^3.1.1
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.5
  go_router: ^6.5.7
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/category/
    - assets/icons/dashboard/

